/* This file was generated by AppSecAI to validate the fix for CWE-78 in scripts/docker-compose.js:38.
Inputs below are representative attacks for this CWE and should be rejected by the fix. Delete or edit this file after review. */
const assert = require('assert');
const maliciousInputs = ["test; cat /etc/passwd", "$(whoami)"];
const safeInputs = ["customer-sync", "daily-report"];

describe('CWE-78 generated negative test', () => {
  it.skip('wire this generated test to the fixed entry point before relying on it in CI', () => {
    assert.ok(maliciousInputs.length > 0);
    assert.ok(safeInputs.length > 0);
  });
});
