/* This file was generated by AppSecAI to validate the fix for CWE-798 in integration/microservices/src/tcp-tls/privkey.pem:1.
Inputs below are representative attacks for this CWE and should be rejected by the fix. Delete or edit this file after review. */
const assert = require('assert');
const maliciousInputs = ["hardcoded-admin-token", "prod-root-password"];
const safeInputs = ["${APPSECAI_TEST_SECRET}", "${CUSTOMER_API_TOKEN}"];

describe('CWE-798 generated negative test', () => {
  it.skip('wire this generated test to the fixed entry point before relying on it in CI', () => {
    assert.ok(maliciousInputs.length > 0);
    assert.ok(safeInputs.length > 0);
  });
});
