version: "3"

services:
  mongodb:
    image: mongo:8.2
    read_only: true
    tmpfs:
      - /tmp
      - /var/run/mongodb
    environment:
      - MONGODB_DATABASE="test"
    ports:
      - 27017:27017